### ISSUE TITLE
Sometimes fails to gather all the necessarry data

### ISSUE THREAD

**Issue by ton31337** [netenglabs/suzieq#428]
**Describe the bug**

Lots of such warnings: `Task was destroyed but it is pending!`

I noticed that this mostly happens with the _slow_ nodes where the latency is 200-300ms. 

**Additional context**

Running command:
```
  ./bin/sq-poller --devices-file "hosts-$DC.yml" \
    --ignore-known-hosts \
    --run-once gather \
    --exclude-services devconfig

  timeout --signal=TERM 10 ./bin/sq-poller --input-dir ./sqpoller-output
```
suzieq/suzieq-cfg.yml:
```
data-directory: ./parquet
temp-directory: /tmp/
poller:
  period: 30
  connect-timeout: 59
  logfile: /tmp/sq-poller.log
```

I expect to have all the data scraped with the first command `run-once` and do the computation later, but seems run-once does not gather all the data sometimes.
