### ISSUE TITLE
Feature Request: Add Ansible Collection

### ISSUE THREAD

**Issue by JulioPDX** [netenglabs/suzieq#469]
Ansible collection could aid in the availability of Suzieq for network operators utilizing the tool in their environments. 

Suzieq already has powerful aver checks to validate the state of interfaces or routing protocols. It would be interesting to have modules that pointed to the parquet directory and allowed checks to be performed. This could also expand to the other filters and tests that can be performed by Suzieq, below is just a concept example.

```yaml
- name: Checking Routing Protocols
  suzieq:
    aver_bgp: True
    aver_ospf: True
    parquet: /tmp/parquet-out
```
