### ISSUE TITLE
NetBox Inventory Advanced Query

### ISSUE THREAD

**Issue by ryanmerolle** [netenglabs/suzieq#641]
**Is your feature request related to a problem? Please describe.**
It would be nice to query NetBox on more than just a tag.

**Describe the solution you'd like**
2 options:

1. Implement a method to grab inventory on status, platform, and all the various attributes useful to people.
2. Allow people to provide an API query to override the default netbox query. **Easiest to implement, and most flexibility** Example inventory source:
```yaml
- name: netbox-dc-01
  type: netbox
  token: your-api-token-here
  url: https://127.0.0.1:8000
  #tag: suzieq-demo    # if not present, default is "suzieq"
  api_override: "platform=cisco-ios&status=active"
  period: 3600        # How frequently Netbox should be polled
  ssl-verify: false   # Netbox certificate validation will be skipped
```

**Additional context**
This would allow people to tweak namespace based on the query and also give people the ability to build inventory based on anything they want in the api.
