### ISSUE TITLE
key-passphrase is not a valid auth config option in the inventory

### ISSUE THREAD

**Issue by ryanmerolle** [netenglabs/suzieq#675]
**Describe the bug**
key-passphrase is not a valid auth config option in the inventory

**To Reproduce**
```yaml
# inventory file

auths:
- name: suzieq-user-04
  key-passphrase: ask
  keyfile: path/to/key
```

 **Actual behavior**
```
suzieq_poller  | - auths.suzieq-user-04:
suzieq_poller  |   + key-passphrase: extra fields not permitted
```

 **Expected behavior**
Should work

**Additional context**
This looks like a bug @LucaNicosia is aware of
