### ISSUE TITLE
[Bug]: inventory - namespace organization should be aligned to yaml sintax standards

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#705]
### Suzieq version

0.17.1

### Install Type

container

### Python version

3.8

### Impacted component

sq-poller

### Steps to Reproduce

1. create a namespace without multiple sources.

### Expected Behavior

the proper way to define the above should be:

```
    namespaces:
      - name: customer1
          - source: nxos-devices
             auth: customer-auth
             device: standard
          - source: ios-devices
             auth: customer-auth
             device: slowhosts
```

### Observed Behavior

Today's inventory needs to be written like this

```
    namespaces:
      - name: customer1
        source: nxos-devices
        auth: customer-auth
        device: standard
      - name: customer1
        source: ios-devices
        auth: customer-auth
        device: slowhosts
```

this doesn't respect proper yaml structures
