### ISSUE TITLE
[Bug]: Processing data failed for service vlan

### ISSUE THREAD

**Issue by FloLaco** [netenglabs/suzieq#808]
### Suzieq version

0.19.1

### Install Type

container

### Python version

3.8

### Impacted component

sq-poller

### Steps to Reproduce

```
host$ export SUZIEQ_NET_PASS=xxxx
host$ docker run -it -e SUZIEQ_NET_PASS -v /home/florian/suzieq/dbdir:/home/suzieq/parquet --name sq-poller --rm  netenglabs/suzieq
container$ cat parquet/inventory.yml
sources:
- name: testbed-native
  type: native
  hosts:
  # - url: ssh://vagrant@10.0.0.1:22 keyfile=/path/to/private_key
  # - url: ssh://vagrant@10.0.0.2:22 devtype=eos keyfile=/path/to/private_key
  - url: ssh://florian_lacommare@x.x.x.x:22 devtype=ios


devices:
- name: devices-with-jump-hosts
  transport: ssh
  jump-host: xxxx@y.y.y.y
  jump-host-key-file: /home/suzieq/parquet/ssh_cred_conf/id_rsa
  ignore-known-hosts: true
  port: 22

auths:
- name: suzieq-user-01
  username: florian_lacommare
  password: plain:test

- name: suzieq-user-02
  username: florian_lacommare
  password: env:SUZIEQ_NET_PASS

# - name: suzieq-user-03
#   username: florian_lacommare
#   password: ask

namespaces:
- name: testing
  source: testbed-native
  device: devices-with-jump-hosts
  auth: suzieq-user-02

container$ sq-poller -I parquet/inventory.yml
```

### Expected Behavior

Should get data

### Observed Behavior

```
2022-10-10 13:21:31,320 - suzieq.poller.controller - WARNING - log level WARNING
[WORKER 0]: 2022-10-10 13:21:32,510 - suzieq.poller.worker - WARNING - log level WARNING
[WORKER 0]: 2022-10-10 13:21:32,919 - suzieq.poller.worker.nodes.node - WARNING - ios supplied for x.x.x.x:22
[WORKER 0]: 2022-10-10 13:21:36,632 - suzieq.poller.worker.services.service - ERROR - Processing data failed for service vlan on node RSWBB-1-001
[WORKER 0]: Traceback (most recent call last):
[WORKER 0]:   File "/usr/local/lib/python3.8/site-packages/suzieq/poller/worker/services/service.py", line 819, in run
[WORKER 0]:     result = self.process_data(output)
[WORKER 0]:   File "/usr/local/lib/python3.8/site-packages/suzieq/poller/worker/services/service.py", line 478, in process_data
[WORKER 0]:     return self.clean_data(result, data)
[WORKER 0]:   File "/usr/local/lib/python3.8/site-packages/suzieq/poller/worker/services/service.py", line 537, in clean_data
[WORKER 0]:     processed_data = dev_clean_fn(processed_data, raw_data)
[WORKER 0]:   File "/usr/local/lib/python3.8/site-packages/suzieq/poller/worker/services/vlan.py", line 161, in _clean_ios_data
[WORKER 0]:     vlan_dict[str(vlan)]['interfaces'].append(ifname)
[WORKER 0]: KeyError: '999'
```
