### ISSUE TITLE
[Bug]: Multiple pollers crash because of coalescer death

### ISSUE THREAD

**Issue by FloLaco** [netenglabs/suzieq#810]
### Suzieq version

0.19.1

### Install Type

container

### Python version

3.8

### Impacted component

sq-poller

### Steps to Reproduce

1. Run 2 pollers, each one with its inventory file
2. Use this config file : 
```
data-directory: ./parquet
temp-directory: /tmp/

rest:
  API_KEY: xxxx
  logging-level: WARNING
  address: 0.0.0.0
  port: 8000

poller:
  logging-level: ERROR
  period: 60
  connect-timeout: 15
  log-stdout: true

coalescer:
  period: 1h
  logging-level: WARNING

```

### Expected Behavior

The poller should not crash if the coalescer is already lock by another poller.

### Observed Behavior

One of the poller is crashing because of the coalescer death : 

```
[COALESCER]: ERROR: Another coalescer process present
2022-10-18 14:10:47,441 - suzieq.poller.worker.coalescer_launcher - ERROR - Maximum number of attempts reached 3/3, the coalescer keep on crashing
2022-10-18 14:10:48,048 - suzieq.poller.controller - ERROR - Unexpected coalescer death
florian@dsrauto-dev1:~
florian@dsrauto-dev1:~$ docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                                            NAMES
39da4bc30b7c        ddutt/suzieq:0.19.3                        "suzieq-gui"             25 minutes ago      Up 25 minutes       0.0.0.0:8501->8501/tcp                           suzieq-gui
4ab7801a9f4b        ddutt/suzieq:0.19.3                        "sq-poller -I parque…"   25 minutes ago      Up 4 minutes                                                         suzieq-poller
c2ee7709e8b2        ddutt/suzieq:0.19.3                        "sq-poller -I parque…"   25 minutes ago      Up 25 minutes                                                        suzieq-poller2
35f73cf467df        ddutt/suzieq:0.19.3                        "sq-rest-server -c p…"   25 minutes ago      Up 25 minutes       0.0.0.0:8502->8000/tcp                           suzieq-api
```

As you can see, the suzieq-poller is up since 4min. And when I was checking log with `-f` option, my log stopped because container was stoped (crash).
