### ISSUE TITLE
[Bug]: when transport https set, defaults to use port 22

### ISSUE THREAD

**Issue by ryanmerolle** [netenglabs/suzieq#865]
### Suzieq version

0.20.1

### Install Type

container

### Python version

3.10

### Impacted component

sq-poller

### Steps to Reproduce

If you uncomment out the port to set it explicitly, everything works.

**inventory.yml**
```yaml
---
sources:
  - name: netbox
    token: TESTTOKEN
    url: https://netbox.example.com/
    tag:
      - test
    type: netbox
    period: 3600

devices:
  - name: devices-using-rest
    transport: https
    #port: 443
    devtype: eos
    ignore-known-hosts: true

auths:
  - name: TACACS
    username: test-username
    password: test-password

namespaces:
  - name: test
    source: netbox
    device: devices-using-rest
    auth: TACACS
```

**Log**
```
suzieq_poller        | [WORKER 0]: 2023-03-06 21:16:27,427 - suzieq.poller.worker.nodes.node - INFO - 192.168.1.1:22 exec: ['show version', 'show hostname']
```

### Expected Behavior

If https transport set, the port should default to 443.

### Observed Behavior

If https transport set, the port defaults to 22.
