### ISSUE TITLE
[Docs]: Transport setting is ignored for Arista EOS devices listed in Ansible inventory

### ISSUE THREAD

**Issue by ipspace** [netenglabs/suzieq#875]
### Change Type

Correction

### Area

Configuration parameters

### Proposed Changes

The Ansible section of Inventory File document (https://suzieq.readthedocs.io/en/latest/inventory/#ansible) mentions REST transport as the assumed transport for Arista EOS devices specified in an Ansible inventory, but does not mention that you cannot override that setting with `transport` parameter of `devices` section.

For example, `sq-poller` still uses REST API to collect data from Arista EOS devices when using the following configuration file:

```
---
sources:
- name: netlab-ansible
  type: ansible
  path: /cfdir/ansible-inventory.json

devices:
- name: ignore-known-hosts
  ignore-known-hosts: true
  transport: ssh

auths:
- name: vagrant
  username: vagrant
  password: plain:vagrant

namespaces:
- name: netlab
  source: netlab-ansible
  device: ignore-known-hosts
  auth: vagrant
```
