### ISSUE TITLE
[Feature]: Define a specific ssh config file

### ISSUE THREAD

**Issue by matheorism** [netenglabs/suzieq#916]
### Suzieq version

0.21.0

### Install Type

None

### Feature type

New component

### Use case

Let's say I have multiple sites and each of those has different options defined in a single ssh config file. The aim is to not populate the default ssh config file.

### Proposed functionality/solution

Perhaps this could be defined in the credentials.yaml as a key-value option

`ssh_config: /path/to/ssh_config_file`

```
- namespace: testing
  devices:
  - hostname: leaf01
    password: my-password
    username: vagrant
  - hostname: leaf02
    keyfile: /path/to/private/key
    ssh_config: /path/to/ssh_config_file  <----
    username: vagrant
  - hostname: leaf03
    keyfile: /path/to/private/key
    username: vagrant
    key-passphrase: my-passphrase
  - address: 10.0.0.1
    username: vagrant
    password: my-password
```
